### ISSUE TITLE
what it is Advantage guzzlehttp

### ISSUE THREAD

**Issue by vahidalvandi** [RTLer/zarinpal-composer-library#9]
hello , very thanks for building zaarinpal driver , i will use it in in webineh company web based software, but have question ! what it is Advantage guzzlehttp In the event that PHP Does not need additional component fot soap !

**Comment by RTLer** [comment]
Hi Vahid,

Thanks for your contribution. In ZarinPal we have 2types of API:

1. Soap Based Webservice
2. RestFul webservice

for this library we created three types of connector:

1. SoapClient backed connector
2. Nusoap backed connector 
3. Guzzle backed connector

Due to speed of SSL handshake and well handling of exceptions we suggest users to use RestFul API so we included Guzzle library to consume our RestFul API.

Hope this clarifying how library works,
Regards
